[package]
name = "metrics-cli"
version = "0.1.0"
authors = ["Clement Delafargue <clement@delafargue.name>"]

[dependencies]
metrics_lib = { path = "../lib" }
structopt = "0.1.0"
structopt-derive = "0.1.0"